<a href="https://colab.research.google.com/github/Shanu06github/20MIS0286/blob/main/Spotify_User_Churn_Pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [12]:
data1=pd.read_csv("spotify_churn_dataset.csv")
data1.head()

user_id  gender  age country subscription_type  listening_time  \
0        1  Female   54      CA              Free              26   
1        2   Other   33      DE            Family             141   
2        3    Male   38      AU           Premium             199   
3        4  Female   22      CA           Student              36   
4        5   Other   29      US            Family             250   

   songs_played_per_day  skip_rate device_type  ads_listened_per_week  \
0                    23       0.20     Desktop                     31   
1                    62       0.34         Web                      0   
2                    38       0.04      Mobile                      0   
3                     2       0.31      Mobile                      0   
4                    57       0.36      Mobile                      0   

   offline_listening  is_churned  
0                  0           1  
1                  1           0  
2                  1           1  
3                  1           0  
4                  1           1

In [14]:
data1=data1.drop('user_id',axis='columns')


KeyError: "['user_id'] not found in axis"

In [16]:
data1.head()

gender  age country subscription_type  listening_time  \
0  Female   54      CA              Free              26   
1   Other   33      DE            Family             141   
2    Male   38      AU           Premium             199   
3  Female   22      CA           Student              36   
4   Other   29      US            Family             250   

   songs_played_per_day  skip_rate device_type  ads_listened_per_week  \
0                    23       0.20     Desktop                     31   
1                    62       0.34         Web                      0   
2                    38       0.04      Mobile                      0   
3                     2       0.31      Mobile                      0   
4                    57       0.36      Mobile                      0   

   offline_listening  is_churned  
0                  0           1  
1                  1           0  
2                  1           1  
3                  1           0  
4                  1           1

In [18]:
target=data1['is_churned']
target.head()

0    1
1    0
2    1
3    0
4    1
Name: is_churned, dtype: int64

In [19]:
data1=data1.drop('is_churned',axis='columns')

In [21]:
data1.head()

gender  age country subscription_type  listening_time  \
0  Female   54      CA              Free              26   
1   Other   33      DE            Family             141   
2    Male   38      AU           Premium             199   
3  Female   22      CA           Student              36   
4   Other   29      US            Family             250   

   songs_played_per_day  skip_rate device_type  ads_listened_per_week  \
0                    23       0.20     Desktop                     31   
1                    62       0.34         Web                      0   
2                    38       0.04      Mobile                      0   
3                     2       0.31      Mobile                      0   
4                    57       0.36      Mobile                      0   

   offline_listening  
0                  0  
1                  1  
2                  1  
3                  1  
4                  1

// Change to catgorical variables
1.   gender
1.  country
2.   subscription_type
2.  device_type



In [22]:
from sklearn.preprocessing import LabelEncoder

In [23]:
le_gender=LabelEncoder()
le_country=LabelEncoder()
le_subscription_type=LabelEncoder()
le_device_type=LabelEncoder()

In [24]:
data1['gender_n']=le_gender.fit_transform(data1['gender'])
data1['country_n']=le_country.fit_transform(data1['country'])
data1['subscription_type_n']=le_subscription_type.fit_transform(data1['subscription_type'])
data1['device_type_n']=le_device_type.fit_transform(data1['device_type'])

In [26]:
data1.head()

gender  age country subscription_type  listening_time  \
0  Female   54      CA              Free              26   
1   Other   33      DE            Family             141   
2    Male   38      AU           Premium             199   
3  Female   22      CA           Student              36   
4   Other   29      US            Family             250   

   songs_played_per_day  skip_rate device_type  ads_listened_per_week  \
0                    23       0.20     Desktop                     31   
1                    62       0.34         Web                      0   
2                    38       0.04      Mobile                      0   
3                     2       0.31      Mobile                      0   
4                    57       0.36      Mobile                      0   

   offline_listening  gender_n  country_n  subscription_type_n  device_type_n  
0                  0         0          1                    1              0  
1                  1         2          2                    0              2  
2                  1         1          0                    2              1  
3                  1         0          1                    3              1  
4                  1         2          7                    0              1

In [28]:
data1=data1.drop(['gender','country','subscription_type','device_type'],axis='columns')

In [30]:
data1.head()

age  listening_time  songs_played_per_day  skip_rate  \
0   54              26                    23       0.20   
1   33             141                    62       0.34   
2   38             199                    38       0.04   
3   22              36                     2       0.31   
4   29             250                    57       0.36   

   ads_listened_per_week  offline_listening  gender_n  country_n  \
0                     31                  0         0          1   
1                      0                  1         2          2   
2                      0                  1         1          0   
3                      0                  1         0          1   
4                      0                  1         2          7   

   subscription_type_n  device_type_n  
0                    1              0  
1                    0              2  
2                    2              1  
3                    3              1  
4                    0              1

// ALGORITHM
1. LOGISTIC REGRESSION
2. DECISION TREE
3. RANDOM FOREST
4. SVM

In [32]:
x=data1
x.head()

age  listening_time  songs_played_per_day  skip_rate  \
0   54              26                    23       0.20   
1   33             141                    62       0.34   
2   38             199                    38       0.04   
3   22              36                     2       0.31   
4   29             250                    57       0.36   

   ads_listened_per_week  offline_listening  gender_n  country_n  \
0                     31                  0         0          1   
1                      0                  1         2          2   
2                      0                  1         1          0   
3                      0                  1         0          1   
4                      0                  1         2          7   

   subscription_type_n  device_type_n  
0                    1              0  
1                    0              2  
2                    2              1  
3                    3              1  
4                    0              1

In [34]:
y=target
y.head()

0    1
1    0
2    1
3    0
4    1
Name: is_churned, dtype: int64

In [65]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [66]:
from sklearn import linear_model
lg=linear_model.LogisticRegression(solver='liblinear')
lg.fit(x_train,y_train)
lg.score(x_test,y_test)

0.7433333333333333

In [67]:
from sklearn import tree
dt=tree.DecisionTreeClassifier()
dt.fit(x_train,y_train)
dt.score(x_test,y_test)

0.6245833333333334

In [68]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.7433333333333333

In [69]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=50)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.7341666666666666

// TRY WITH CROSS VALIDATION

from sklearn.model_selection import cross_val_score

cross_val_score(logisticRegression(),x,y,cv=3)
cross_val_score(DecisionTreeClassifier(),x,y,cv=3)
cross_val_score(svc(),x,y,cv=3)
cross_val_score(RandomForestClassifier(n_estimator=40),x,y,xv=3)

In [70]:
from sklearn.model_selection import cross_val_score


In [75]:
cross_val_score(SVC(),x,y,cv=8)


array([0.741, 0.741, 0.741, 0.741, 0.741, 0.741, 0.741, 0.742])

In [72]:
cross_val_score(tree.DecisionTreeClassifier(),x,y,cv=10)

array([0.60875, 0.5875 , 0.59125, 0.60625, 0.6225 , 0.5975 , 0.59375,
       0.63625, 0.61125, 0.57875])

In [76]:
cross_val_score(linear_model.LogisticRegression(solver='liblinear',max_iter=1000),x,y,cv=10)

array([0.74   , 0.74125, 0.74125, 0.74125, 0.74125, 0.74125, 0.74125,
       0.74125, 0.74125, 0.74125])

In [80]:
score_rf=cross_val_score(RandomForestClassifier(n_estimators=20),x,y,cv=100)
score_rf

array([0.7   , 0.725 , 0.7   , 0.7375, 0.725 , 0.7   , 0.75  , 0.75  ,
       0.7375, 0.7375, 0.7125, 0.725 , 0.7125, 0.7375, 0.675 , 0.725 ,
       0.7125, 0.7125, 0.725 , 0.725 , 0.7125, 0.7375, 0.725 , 0.75  ,
       0.7125, 0.725 , 0.7   , 0.725 , 0.7125, 0.7375, 0.725 , 0.7375,
       0.7125, 0.7375, 0.7   , 0.725 , 0.725 , 0.725 , 0.7125, 0.7375,
       0.7375, 0.7   , 0.7   , 0.7125, 0.75  , 0.7   , 0.7375, 0.7125,
       0.75  , 0.7375, 0.7375, 0.725 , 0.6875, 0.7125, 0.7   , 0.7   ,
       0.75  , 0.7375, 0.7   , 0.75  , 0.7375, 0.7125, 0.7375, 0.7375,
       0.7125, 0.7375, 0.7125, 0.7125, 0.7625, 0.7375, 0.7375, 0.7625,
       0.7625, 0.75  , 0.7375, 0.7625, 0.75  , 0.725 , 0.7125, 0.725 ,
       0.7125, 0.725 , 0.7375, 0.725 , 0.75  , 0.75  , 0.7375, 0.7375,
       0.7375, 0.7125, 0.75  , 0.7375, 0.725 , 0.7375, 0.75  , 0.725 ,
       0.7375, 0.7125, 0.75  , 0.75  ])

In [82]:
(score_rf.mean())

np.float64(0.7276250000000001)